### ISSUE TITLE
[Q] About adding a license for documents

### ISSUE THREAD

**Issue by RinLin-NYA** [AndroidPatch/APatchDocs#13]
为了更好的规避一些版权问题，并更好的促进文档贡献，我建议为这个仓库设置一个 license 来规范文档的使用
例如 CC-BY / CC-BY-SA / CC-BY-NC / GNU FDL 这一类的 license，这样可以避免很多问题
不知道各位意下如何（

To avoid some copyright issues and promote contribution of documents, I propose to set a license to standardize the usage of documents.
For example, CC-BY / CC-BY-SA / CC-BY-NC / GNU FDL, so it can avoid many issues.
How do you feel about this?(

@NightSong-UwU @AtopesSayuri @igormiguell

**Comment by AtopesSayuri** [comment]
*~~JUST DO IT~~*

**Comment by igormiguell** [comment]
no problem

**Comment by RinLin-NYA** [comment]
It seems that all contributors has no objection about this, so I will start to license this repository and all its documents under CC-BY-SA 4.0.
