### ISSUE TITLE
Installation page doesn't mention anything about "AndroidPatch"

### ISSUE THREAD

**Issue by dhyanKaro** [AndroidPatch/APatchDocs#134]
So it's not clear to me if I should press the Install button there or if I need that or not.

**Comment by RinLin-NYA** [comment]
Could you tell me in which part of "Installation" let you doubted?

**Comment by dhyanKaro** [comment]
> Could you tell me in which part of "Installation" let you doubted?
The purpose of the AndroidPatch Install button

**Comment by RinLin-NYA** [comment]
> > Could you tell me in which part of "Installation" let you doubted?
> 
> The purpose of the AndroidPatch Install button

That button is the button displayed in the manager, it equals to "install"
