### ISSUE TITLE
[T] Todo: Update Brazilian Portuguese and Russian translations of faq.md

### ISSUE THREAD

**Issue by RinLin-NYA** [AndroidPatch/APatchDocs#19]
The faq.md in Chinese and English has been updated in commit 1ec631b, and it needs updates for other languages.
We need your help to finish this todo, thank you for your contribution in advance.

**Comment by RinLin-NYA** [comment]
@igormiguell @xteamlyer Are you interested in updating the translations about faq.md? Thank you for your contribution in advance.

**Comment by RinLin-NYA** [comment]
After this todo finished, these docs may have no changes in a long period, our work will be admitted by APatch official, and this repository will become the official docs of APatch. Go for it!

**Comment by xteamlyer** [comment]
> @igormiguell @xteamlyer Are you interested in updating the translations about faq.md? Thank you for your contribution in advance.

Hi! Opened PR to update FAQ in Russian #20

**Comment by igormiguell** [comment]
updated

**Comment by RinLin-NYA** [comment]
Pull request #20 and #21 merged, this issue will be closed.
