### ISSUE TITLE
New translation request

### ISSUE THREAD

**Issue by AtopesSayuri** [AndroidPatch/APatchDocs#22]
The documentation has been updated. A new page was added.
Check [/docs/zh_CN/apm-guide.md](https://github.com/AndroidPatch/APatchDocs/blob/main/docs/zh_CN/apm-guide.md)

@xteamlyer @RinLin-NYA @igormiguell 

Update: English and Russian translation has been completed by @xteamlyer .
Update 2: Brazilian Portuguese translation has been completed by @igormiguell . This issue will be closed.

**Comment by RinLin-NYA** [comment]
ok, i will start to translate the English version immediately

**Comment by xteamlyer** [comment]
> ok, i will start to translate the English version immediately

Check this #23
Maybe it needs to be edited

**Comment by RinLin-NYA** [comment]
> > ok, i will start to translate the English version immediately
> 
> Check this #23 Maybe it needs to be edited

hmmm......
I will stop translating and turn to review your pr now

**Comment by igormiguell** [comment]
translated
