### ISSUE TITLE
Add a new patch method on web

### ISSUE THREAD

**Issue by affggh** [AndroidPatch/APatchDocs#25]
See demos [here](https://kernelpatch-on-web.pages.dev/)    
Based on cloudflare pages, runs on browser env.    
Source from [here](https://github.com/affggh/kernelpatch_on_web)

Suggest use latest firefox or edge

Screen shots here:    
![Screenshot_2024-05-07-00-30-37-40_df198e732186825c8df26e3c5a10d7cd](https://github.com/AndroidPatch/APatchDocs/assets/46290091/e1e5db55-e07a-461e-8ce4-8e3a7d21da4a)

**Comment by affggh** [comment]
It not stable after all,so I guess it should marked with unstable

**Comment by affggh** [comment]
Im already verified on my oneplus 6t(fajita)
and looks worked fine

**Comment by AtopesSayuri** [comment]
pls wait. let me found more testers.

and thanks for your contribution to APatch project!
