### ISSUE TITLE
Todo: Update patch.md

### ISSUE THREAD

**Issue by AkinaAcct** [AndroidPatch/APatchDocs#26]
A new patching method has been added. Document maintainers please update the relevant parts.

check [/docs/zh_CN/patch.md#L87](https://github.com/AndroidPatch/APatchDocs/blob/07da101999f829208fdd4d8d994e2fd008668e0c/docs/zh_CN/patch.md?plain=1#L87) for details.

Note: this is a small change(Only 3 line). It doesn't really need to be updated anytime soon.

Update 1: The English and Brazilian Portuguese version have been translated in #27. We still need a Russian translation.

Update 2: The Russian version has been translated in #29. This issue will be closed.

**Comment by igormiguell** [comment]
look #27
