### ISSUE TITLE
Todo: new doc update.md

### ISSUE THREAD

**Issue by AkinaAcct** [AndroidPatch/APatchDocs#28]
A new page has been added. Relevant translation work requires follow-up by contributors.

@xteamlyer @RinLin-NYA @igormiguell 

check [/docs/zh_CN/update.md](https://github.com/AndroidPatch/APatchDocs/blob/main/docs/zh_CN/update.md) for more details.

Also, don't forget #26 :)

**Comment by xteamlyer** [comment]
Check #29

**Comment by RinLin-NYA** [comment]
All translation have been completed. This issue will be closed.
