### ISSUE TITLE
TODO: Translate the new page rescue-bootloop.md

### ISSUE THREAD

**Issue by AkinaAcct** [AndroidPatch/APatchDocs#35]
A page about APatch's brick recovery mechanism (safe mode) has been added.

check [/docs/zh_CN/rescue-bootloop.md](https://github.com/AndroidPatch/APatchDocs/blob/main/docs/zh_CN/rescue-bootloop.md) for more details.

Also, there are some errors in the sidebar ordering in other language versions than the Chinese documentation: it places apm-guide at the end. This is incorrect, please follow the relevant section in zh_CN to change it.

Thank you for your contribution!

**Comment by igormiguell** [comment]
#36

**Comment by xteamlyer** [comment]
#37
