### ISSUE TITLE
TODO: translate the new page kpm-guide

### ISSUE THREAD

**Issue by AkinaAcct** [AndroidPatch/APatchDocs#46]
A new page was added in #45 

@xteamlyer @igormiguell @RinLin-NYA 

Some translation work needs to be done.

See [docs/zh_CN/kpm-usage-guide.md](https://github.com/AndroidPatch/APatchDocs/blob/main/docs/zh_CN/kpm-usage-guide.md) for details.

Thanks in advance for your contributions!

**Comment by RinLin-NYA** [comment]
English version is completed, see commit ce08dab for details.

**Comment by igormiguell** [comment]
#48

**Comment by xteamlyer** [comment]
#49

**Comment by RinLin-NYA** [comment]
All parts was done.
